export const tableheaders = [
  "ID Number",
  "Name",
  "Screen Name",
  "Gender",
  "Basic Salary",
  // "Civil Status",
  // "Address",
  // "Contact Number",
  // "Email",
  // "SSS Number",
  // "PhilHealth Number",
  // "Pag-IBIG Number",
  // "TIN",
  // "Date of Birth",
  // "Position",
  // "Department",
  // "Date Hired",
  // "Employment Type",
  // "Payment Method",
  // "Bank Account No.",
];
