export const tableheaders = [
  "First Name",
  "Middle Name",
  "Last Name",
  "Gender",
  "Civil Status",
  "Address",
  "Contact Number",
  "Email",
  "SSS Number",
  "PhilHealth Number",
  "Pag-IBIG Number",
  "TIN",
  "Date of Birth",
  "Position",
  "Department",
  "Date Hired",
  "Employment Type",
  "Basic Salary",
  "Payment Method",
  "Bank Account No.",
];
